### PR TITLE
[#180] Trim whitespaces from submitted branch name

### LINKED ISSUE #180: Trim white spaces off branch names when input in the dockup deployment page
Issue:
In the deployment page when we are asked to input the branch to deploy, if the input has whitespace in the branch name it fails to pick it up. For, eg: ' test_branch' instead of 'test_branch'.

Expected:
The branch should be picked up irrespective of the whitepsaces

### PR DESCRIPTION
**Pull request by manuraj17**
Fixes #180.

- Trims the branch name which is submitted, hence preventing clone failures.

### CODE REVIEW

File: apps/dockup_ui/web/static/js/components/deployment_form.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ class DeploymentForm extends Component {
   }
 
   handleBranchChange(branch) {
-    this.setState({branch: branch});
+    this.setState({branch: branch.trim()});
```
Comment (amit-mb) [inline apps/dockup_ui/web/static/js/components/deployment_form.js]: One thing to keep in mind. Doing this won't let the user type any spaces, which may be a good thing as we don't have any spaces in branch names

Comment (manuraj17) [reply apps/dockup_ui/web/static/js/components/deployment_form.js]: Got it. 👍 
Yeah, since git doesn't support spaces in branch names I think we are good.
